general:
  # If vault is enabled, player win POINTS from match and use POINTS to buy things.
  # Only enable this when you want player spend their money from Quake in other worlds. If you don't know what is Vault, don't enable it.
  vault:
    enabled: false
    win: 100
    kill: 10
  # If vault is disabled, player win POINTS and COINS from match and use COINS to buy things.
  coins:
    win: 100
    kill: 10
  points:
    win: 50
    kill: 5
  # If stats is enabled, players can see their stats scoreboard when they are in lobby.
  # Require a lobby first. Use '/quake setlobby' to set one.
  stats:
    enabled: false
  shop:
    enabled: true
    emerald: false
  # Player got this score in match wins
  winning-points: 25
  # Waiting time before match starts when amount of players meet minimum/maximum requirement of that arena
  min-waiting-time: 10
  max-waiting-time: 10
  # Players wait this time to auto leave the arena after someone wins
  after-waiting-time: 10
railguns:
  wood:
    # Reload time in milliseconds
    reload: 1500
    # Range in blocks
    range: 15
    # Explosion
    explosion:
      enabled: false
      # Only create explosion when you kill others, instead of creating explosion on every shoot
      only-when-hit: true
      # Control the sound and size of the explosion. TNT's power is 4.
      power: 4
    # Firework
    firework:
      enabled: true
      # Colors of firework. You can find the color list on Quake Deathmatch page.
      color: RED
      # Type of firework. You can find the type list on Quake Deathmatch page.
      type: BALL
  stone:
    price: 1800
    reload: 1400
    range: 35
    explosion:
      enabled: false
      power: 2
    firework:
      enabled: true
      color: RED
      type: BALL_LARGE
  iron:
    price: 3500
    reload: 1300
    range: 50
    explosion:
      enabled: true
      power: 1
    firework:
      enabled: true
      color: SILVER
      type: BALL_LARGE
  gold:
    price: 8000
    reload: 1200
    range: 75
    explosion:
      enabled: true
      power: 2
    firework:
      enabled: true
      color: LIME
      type: CREEPER
  diamond:
    price: 15000
    reload: 1100
    range: 100
    explosion:
      enabled: true
      power: 4
    firework:
      enabled: true
      color: AQUA
      type: BALL_LARGE
arenas:
  enabled-arenas: []
players: []